version: '3.8'

services:
  redis:
    image: redis:7.4.1-alpine
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

  web:
    build:
      context: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - redis

  worker:
    build:
      context: .
    command: celery -A app.tasks worker --loglevel=info
    volumes:
      - .:/app
    environment:
      - REDIS_URL=redis://redis:6379
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - redis

volumes:
  redis_data: