# version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - REDIS_URL=redis://redis:6379/0
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - redis
      - worker
    command: ./scripts/server.sh

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - REDIS_URL=redis://redis:6379/0
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    env_file:
      - .env
    depends_on:
      - redis
    command: ./scripts/worker.sh

  redis:
    image: redis:7.4.1-alpine
    ports:
      - 6379:6379
